Controllers/DambelController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class DambelController : Controller 
    {
        private readonly IDambelRepositoy _dambelRepositoy;
        private readonly ICategoryRepositorycs _categoryRepositorycs;

        public DambelController(IDambelRepositoy dambelRepositoy, ICategoryRepositorycs categoryRepositorycs)
        {
            _dambelRepositoy = dambelRepositoy;
            _categoryRepositorycs = categoryRepositorycs;
        }

        public IActionResult List()
        {
            //ViewBag.CurrentCategory = "Best Sellers";
            //return View(_dambelRepositoy.GetAllDambels);
            var DambelListViewModel = new DambelListViewModel();
            DambelListViewModel.Dambels = _dambelRepositoy.GetAllDambels;
            DambelListViewModel.CurrentCategory = "Best sellers";
            return View(DambelListViewModel);

        }

        public IActionResult Details(int Id)
        {
            var Dambel = _dambelRepositoy.GetDambel(Id);
            if (Dambel == null)
                return NotFound();
            return View(Dambel);
        }
        
    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly IDambelRepositoy _dambelRepositoy;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IDambelRepositoy dambelRepositoy , ShoppingCart shoppingCart)
        {
            _dambelRepositoy = dambelRepositoy;
            _shoppingCart = shoppingCart;
        } 

        public ViewResult Index()
        {
            // this part of code is  weird 
            _shoppingCart.ShoppingCartItem = _shoppingCart.GetShoppingCartItems();
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                shoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()

            };
            return View(shoppingCartViewModel);
           
        }

        // this action just adds a item to the shopping cart and return the same view ( the index view but updated )
        public RedirectToActionResult AddToShoppingCart(int dambelId)

        // why can i use Where instead of FirstOrDefaul in this line of code ?
        {
            var selectedDambel = _dambelRepositoy.GetAllDambels.FirstOrDefault(s => s.DambelId == dambelId);
            if (selectedDambel != null)
            {
                _shoppingCart.AddToCart(selectedDambel, 1);
            }

            return RedirectToAction("Index");
        }


        public RedirectToActionResult RemoveFromShoppingCart(int dambelId)
        {
            var selectedDambel = _dambelRepositoy.GetAllDambels.FirstOrDefault(s => s.DambelId == dambelId);
            if ( selectedDambel != null)
            {
                _shoppingCart.RemoveFromCart(selectedDambel);
            }
            return RedirectToAction("Index");
        }


    }
}

Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Views/Shared/_DambelCard.cshtml
@model Dambel


<div class="col-sm-4 col-md-4 col-lg-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="Image for Dambel" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Dambel" asp-action="Details" asp-route-Id="@Model.DambelId">@Model.Name</a></h3>
            <h3>@Model.Desciption</h3>
        </div>
        <div class="addToCart">
            <p >
                <a class="btn btn-primary"  asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-dambelId="@Model.DambelId"> Add to Cart</a>
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Dambel" asp-action="List">All Dambels</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/Images/logo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>

        </div>
        
    </div>
</body>
</html>